services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecretlongpassword
      POSTGRES_USER: root
    ports:
      - 5440:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

volumes:
  redis-data:
